/**
 * AI Service — Anthropic Claude
 *
 * This file maintains the same exports (generateText, checkGeminiConfiguration)
 * so all downstream services work without changes. Under the hood it calls
 * the Anthropic Messages API instead of Gemini.
 */

const CLAUDE_MODEL = 'claude-sonnet-4-20250514';
const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';

export interface GenerateTextOptions {
  maxTokens?: number;
  temperature?: number;
  topP?: number;
}

const FEATURE_TOKEN_LIMITS: Record<string, number> = {
  patent_specification: 4096,
  patent_claims: 4096,
  patent_prior_art_search: 4096,
  patent_drawings: 2048,
  cpc_classification: 2048,
  codebase_analysis: 4096,
  feature_synthesis: 4096,
  copyright_analysis: 2048,
  trademark_analysis: 2048,
  default: 2048,
};

function getApiKey(): string {
  const key = import.meta.env.VITE_ANTHROPIC_API_KEY;
  if (!key) throw new Error('VITE_ANTHROPIC_API_KEY not configured. Add it to your .env file.');
  return key;
}

/** Kept for backward compat — all services call this to check readiness */
export function checkGeminiConfiguration(): { configured: boolean; error?: string } {
  try {
    getApiKey();
    return { configured: true };
  } catch {
    return { configured: false, error: 'Anthropic API key not set' };
  }
}

export async function generateText(
  prompt: string,
  featureArea?: string,
  options?: GenerateTextOptions
): Promise<string> {
  const apiKey = getApiKey();
  const maxTokens = options?.maxTokens || FEATURE_TOKEN_LIMITS[featureArea || 'default'] || 2048;
  const temperature = options?.temperature ?? 0.3;

  const response = await fetch(ANTHROPIC_API, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: maxTokens,
      temperature,
      messages: [
        { role: 'user', content: prompt },
      ],
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    if (response.status === 429) {
      throw new Error('Rate limit exceeded. Please wait a moment and try again.');
    }
    if (response.status === 401) {
      throw new Error('Invalid Anthropic API key. Check your VITE_ANTHROPIC_API_KEY.');
    }
    throw new Error(`Claude API error (${response.status}): ${errorBody}`);
  }

  const data = await response.json();
  const text = data?.content?.[0]?.text;
  if (!text) throw new Error('No text generated by Claude');
  return text;
}
